general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
}

# USER
label {
    monitor = 
    text =    $USER
    font_size = 20
    font_family = $font
    font_color = rgb(143, 143, 143)

    position = 0, -150
    halign = center
    valign = center
}

input-field {
    monitor = 
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0)

    outer_color = rgba(122, 162, 247, 0.9) rgba(187, 154, 247, 0.9) 45deg
    check_color = rgba(73, 218, 202, 0.9) rgba(125, 207, 255, 0.9) 120deg
    fail_color  = rgba(247, 118, 142, 0.9) rgba(255, 165, 180, 0.9) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    dots_spacing = 0.3

    position = 0, -220
    halign = center
    valign = center
    fade_on_empty = true
}

# Time-Hour
label {
    monitor = 
    text = cmd[update:1000] echo "<span>$(date +"%H")</span>"
    color = rgba(255, 255, 255, 1)
    font_size = 125
    font_family = StretchPro
    position = -80, 190
    halign = center
    valign = center
}

# Time-Minute
label {
    monitor = 
    text = cmd[update:1000] echo "<span>$(date +"%M")</span>"
    color = rgba(122, 162, 247,1)
    font_size = 125
    font_family = StretchPro
    position = 0, 70
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor = 
    text = cmd[update:1000] echo -e "$(date +"%d %B")"
    color = rgba(255, 255, 255, 100)
    font_size = 22
    font_family = Suisse Int'l Mono
    position = 20, -8
    halign = center
    valign = center
}

# Degrees
label {
    monitor = 
    text = cmd[update:18000000] echo "<b>Feels like<big> $(curl -s 'wttr.in?format=%t' | tr -d '+') </big></b>"
    color = rgb(143, 143, 143)
    font_size = 18
    font_family = Suisse Int'l Mono

    position = 0, 40
    halign = center
    valign = bottom
}